
before_install:
 - sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
 - sudo apt-get update -qq && sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring && sudo apt-get update -qq
 - sudo apt-get install -qq libxxf86vm-dev libpng12-dev libjpeg8-dev libjpeg-turbo8-dev libopenal-dev libmad0-dev libogg-dev libvorbis-dev libassimp-dev liblua5.1-0-dev dmd-bin libphobos2-dev
 
script:
 - ./create_project.sh gmake
 - make -j8
